name: ExoticGarden
version: ${project.version}
author: TheBusyBiscuit
description: A Slimefun Addon that adds new Plants and dishes to the game
website: https://github.com/TheBusyBiscuit/ExoticGarden

api-version: '1.14'
main: io.github.thebusybiscuit.exoticgarden.ExoticGarden

depend:
- Slimefun